name: projects
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.2

  # State Management
  flutter_riverpod: ^3.3.2

  # Routing
  go_router: ^17.0.0

  # Firebase / Social Login
  firebase_core: ^3.15.2
  firebase_auth: ^5.7.0
  flutter_facebook_auth: ^7.1.6
  flutter_line_sdk: ^2.6.2
  google_sign_in: ^6.2.1

  # Network
  dio: ^5.10.0
  pretty_dio_logger: ^1.4.0
  connectivity_plus: ^6.1.5

  # Local Storage
  flutter_secure_storage: ^10.3.1
  shared_preferences: ^2.5.3

  # JSON / Model
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/logo/
    - assets/images/banners/
    - assets/images/driver/
    - assets/images/placeholder/
    - assets/icons/
    - assets/svg/
    - assets/animations/