// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQ7n1hnVa73NsG_7aGz3HHkPw3EO-EquQ',
    appId: '1:79528000892:web:5a6147e1a0854acefdf8f9',
    messagingSenderId: '79528000892',
    projectId: 'app018-f7783',
    authDomain: 'app018-f7783.firebaseapp.com',
    storageBucket: 'app018-f7783.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChaV7lDcpw4SfRLvKu64gw7lxHx2gF9Fc',
    appId: '1:79528000892:android:8501e075f0b3e5c3fdf8f9',
    messagingSenderId: '79528000892',
    projectId: 'app018-f7783',
    storageBucket: 'app018-f7783.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAekVDDWQVCyDFObz_8PAawzfAs5WxViO0',
    appId: '1:79528000892:ios:07a2a549afb45854fdf8f9',
    messagingSenderId: '79528000892',
    projectId: 'app018-f7783',
    storageBucket: 'app018-f7783.firebasestorage.app',
    androidClientId:
        '79528000892-gpt7ughss1bof3haj5d2436hqqubt9vb.apps.googleusercontent.com',
    iosClientId:
        '79528000892-km8stem3abj3nbkglndnm8a9na8vscpd.apps.googleusercontent.com',
    iosBundleId: 'com.example.projects',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAekVDDWQVCyDFObz_8PAawzfAs5WxViO0',
    appId: '1:79528000892:ios:07a2a549afb45854fdf8f9',
    messagingSenderId: '79528000892',
    projectId: 'app018-f7783',
    storageBucket: 'app018-f7783.firebasestorage.app',
    androidClientId:
        '79528000892-gpt7ughss1bof3haj5d2436hqqubt9vb.apps.googleusercontent.com',
    iosClientId:
        '79528000892-km8stem3abj3nbkglndnm8a9na8vscpd.apps.googleusercontent.com',
    iosBundleId: 'com.example.projects',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQGoIH-Z1niqoQVa9LEiOlf48k2ocDSwA',
    appId: '1:79528000892:web:dc70ab9f80fe0bb7fdf8f9',
    messagingSenderId: '79528000892',
    projectId: 'app018-f7783',
    authDomain: 'app018-f7783.firebaseapp.com',
    storageBucket: 'app018-f7783.firebasestorage.app',
  );
}
